INSERT INTO GENERAL.GTVNTYP (GTVNTYP_CODE, GTVNTYP_DESC, GTVNTYP_ACTIVITY_DATE, GTVNTYP_SURROGATE_ID, GTVNTYP_VERSION, GTVNTYP_USER_ID, GTVNTYP_DATA_ORIGIN, GTVNTYP_VPDI_CODE) VALUES ('UIC', 'Unique Identification Code', TO_DATE('2011-02-25', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, null, null, null)
/
INSERT INTO GENERAL.GTVNTYP (GTVNTYP_CODE, GTVNTYP_DESC, GTVNTYP_ACTIVITY_DATE, GTVNTYP_SURROGATE_ID, GTVNTYP_VERSION, GTVNTYP_USER_ID, GTVNTYP_DATA_ORIGIN, GTVNTYP_VPDI_CODE) VALUES ('FAVD', 'Ethos favored name type', TO_DATE('2020-06-18 15:50:19', 'YYYY-MM-DD HH24:MI:SS'), 2, 0, 'BASELINE', 'Banner', null)
/
