CREATE TABLE GENERAL.GTVCCRD
(
    GTVCCRD_CODE                 VARCHAR2(10 char) NOT NULL
        CONSTRAINT PK_GTVCCRD
            PRIMARY KEY,
    GTVCCRD_DESC                 VARCHAR2(60 char) NOT NULL,
    GTVCCRD_USER_ID              VARCHAR2(30 char) NOT NULL,
    GTVCCRD_ACTIVITY_DATE        DATE              NOT NULL,
    GTVCCRD_EXTERNAL_MERCHANT_ID VARCHAR2(30 char),
    GTVCCRD_SURROGATE_ID         NUMBER(19)        NOT NULL
        CONSTRAINT UK_GTVCCRD_SURROGATE_ID
            UNIQUE,
    GTVCCRD_VERSION              NUMBER(19)        NOT NULL,
    GTVCCRD_DATA_ORIGIN          VARCHAR2(30 char),
    GTVCCRD_VPDI_CODE            VARCHAR2(6 char)
)
/

COMMENT ON TABLE GENERAL.GTVCCRD IS 'CREDIT CARD TYPE Validation Table'
/

COMMENT ON COLUMN GENERAL.GTVCCRD.GTVCCRD_CODE IS 'CREDIT CARD TYPE CODE: Credit Card Type Code for Credit Card Type.'
/

COMMENT ON COLUMN GENERAL.GTVCCRD.GTVCCRD_DESC IS 'DESCRIPTION: Description of the Credit Card Type.'
/

COMMENT ON COLUMN GENERAL.GTVCCRD.GTVCCRD_USER_ID IS 'USER IDENTIFICATION: The unique identification of the user creating or updating the record.'
/

COMMENT ON COLUMN GENERAL.GTVCCRD.GTVCCRD_ACTIVITY_DATE IS 'ACTIVITY DATE: The date that the record was created or updated.'
/

COMMENT ON COLUMN GENERAL.GTVCCRD.GTVCCRD_EXTERNAL_MERCHANT_ID IS 'EXTERNAL MERCHANT ID: The external value for the related internal merchant value.'
/

COMMENT ON COLUMN GENERAL.GTVCCRD.GTVCCRD_SURROGATE_ID IS 'SURROGATE ID: Immutable unique key'
/

COMMENT ON COLUMN GENERAL.GTVCCRD.GTVCCRD_VERSION IS 'VERSION: Optimistic lock token.'
/

COMMENT ON COLUMN GENERAL.GTVCCRD.GTVCCRD_DATA_ORIGIN IS 'DATA ORIGIN: Source system that created or updated the data.'
/

COMMENT ON COLUMN GENERAL.GTVCCRD.GTVCCRD_VPDI_CODE IS 'VPDI CODE: Multi-entity processing code.'
/